// Processing v.2 code for the UR-5: initially developed March 2014 
// at the Applied Research Lab in the Office of the CTO at Autodesk
// by Maurice Conti, Stéphane Bersot, and Dr. Woohoo!


class URScript {
  String pathURScript;
  
  URScript() {}
  
/*
def P3_waypoints():
  $ 1 "Robot Program"
  $ 2 "MoveL"
  $ 3 "Waypoint_1"
  movel([0.233482402859287, 0.11107299840217165, -0.9165273408226376, -2.932487564150296, -1.0803336582214582, -1.079486900826545], a=1.2, v=0.25)
  $ 4 "Waypoint_2"
  movel([-0.014954925709319333, 0.029179069153871313, -1.5701746746885858, -2.926364190879074, -1.080307024480029, -1.0794957787403554], a=1.2, v=0.25)
end  
*/
  
  /*
   * movel(pose, a=1.2, v=0.3, t=0, r=0)
   * 
   * Parameters
   * pose: target pose (pose can also be specified as joint positions, then forward kinematics is used to calculate the corresponding pose)
   *
   * A pose is given as p[x,y,z,ax,ay,az], where x,y,z is 
   * the position of the TCP, and ax,ay,az is the orientation 
   * of the TCP, given in axis-angle notation.
   *   
   * a: tool acceleration [m/sˆ2]. default=1.2 
   * v: tool speed [m/s]. default=0.3
   * t: time [S]. default=0
   * r: blend radius [m]. default=0
   *
   */
   
  String createScript(float[] incomingWayPoints){
    println("create it!");
    // println("incomingWayPoints.length: " +incomingWayPoints.length);

    pathURScript = "def P3_AutoGenerated():"+"\n";
    pathURScript += "  $ 1 \"Robot Program\""+"\n";
    pathURScript += "  $ 2 \"MoveL\""+"\n";
        
    float ax = PI;
    float ay = radians(0.0);
    float az = radians(0.0);
    float v = 2;
    int currentLine = 3;
    int currentWayPoint = 1;
    for (int i = 0; i < incomingWayPoints.length; i+=3)
    {
       //println(i+": " + incomingWayPoints[i]);
       //  $ 3 "Waypoint_1"
       pathURScript += "  $ "+currentLine+" \"Waypoint_"+currentWayPoint+"\""+"\n";
       
       pathURScript += "  movel(p["+incomingWayPoints[i]+", "+incomingWayPoints[i+1]+", "+incomingWayPoints[i+2]+", "+
       ax+", "+ay+", "+az+"], a=2, v="+v+", t=0.0, r=0.002)"+"\n";
       currentLine++;
       currentWayPoint++;
    }
    pathURScript += "end\n";
    
    return pathURScript;
  }

  String returnScript() {
    return pathURScript;
  }
 
  void saveScript() {
  }
}